# Generated by Django 5.2.12 on 2026-04-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictedurl',
            name='max_age',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='restrictedurl',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
    ]
